steps:
  ##########################################  Backend Deployment Start ##########################################

  #build the dockerfile in the backend directory
  - name: 'gcr.io/cloud-builders/docker'    
    args: ['build', '-t', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-backend/uploaded-mern-backend-image:$SHORT_SHA', '.']
    dir: 'backend'
    
  # push the backend image to google container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-backend/uploaded-mern-backend-image:$SHORT_SHA']
    dir: 'backend'

  #######################################
  #   - CLOUD RUN BACKEND DEPLOYMENT
  #######################################
  # deploy the backend image to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cr-mern-backend', '--image', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-backend/uploaded-mern-backend-image:$SHORT_SHA', '--platform', 'managed', '--region', 'us-west1', '--allow-unauthenticated']
    dir: 'backend'

  # #get deployment url and write it to workspace
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: /bin/bash
  #   args: ['-c', 'gcloud run services describe cr-mern-backend --format="value(status.url)" --region=us-west1 > workspace/url.txt']
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud run services describe cr-mern-backend
        --format='value(status.url)' --region=us-west1 > /workspace/url.txt
    entrypoint: /bin/bash
      
  # #print the deployment url
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args: ['-c', 'cat workspace/backend-url.txt']

  #######################################
  #   - KUBERNETES BACKEND DEPLOYMENT
  #######################################
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['set', 'image', 'deployment', 'react-deployment', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-backend/uploaded-mern-backend-image:$SHORT_SHA']

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=k8s/node-deployment.yaml'
      - >-
        --image=us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-backend/uploaded-mern-backend-image:$SHORT_SHA
      - '--location=us-west1'
      - '--cluster=mern-workout-cluster'
      - '--output=./node-output'


##########################################  Backend Deployment Done ##########################################




##########################################  Frontend Deployment Start ##########################################

  #build the dockerfile in the frontend directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA', '.']
    dir: 'frontend'
  # push the frontend image to google container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA']
    dir: 'frontend'
  # deploy the frontend image to cloud run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'cr-mern-frontend', '--image', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA', '--platform', 'managed', '--region', 'us-west1', '--allow-unauthenticated', '--update-env-vars="REACT_APP_BASE_URL=$( < /workspace/url.txt)"']
  #   dir: 'frontend'
  
  #######################################
  #   - CLOUD RUN FRONTEND DEPLOYMENT
  #######################################
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        gcloud run deploy cr-mern-frontend
        --image=us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA
        --platform=managed --region=us-west1 --allow-unauthenticated
        --update-env-vars="REACT_APP_BASE_URL=$( < /workspace/url.txt)"
    dir: frontend
    entrypoint: /bin/bash
  # #get deployment url and write it to workspace
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'services', 'describe', 'cr-mern-frontend', '--platform', 'managed', '--region', 'us-west1', '--format', 'value(status.url)']

  #######################################
  #   - KUBERNETES FRONTEND DEPLOYMENT
  #######################################
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=k8s/react-deployment.yaml'
      - >-
        --image=us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA
      - '--location=us-west1'
      - '--cluster=mern-workout-cluster'
      - '--output=./react-output'

##########################################  Frontend Deployment Done ##########################################

options:
  logging: CLOUD_LOGGING_ONLY




  