steps:
  #build the dockerfile in the frontend directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA', '.']
    dir: 'frontend'
  # push the frontend image to google container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/mern-cloud-run-cloud-build/ar-mern-frontend/uploaded-mern-frontend-image:$SHORT_SHA']
    dir: 'frontend'
options:
  logging: CLOUD_LOGGING_ONLY



  