apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "mern-ip"
    kubernetes.io/ingress.allow-http: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
  - host: frontend.endpoints.mern-cloud-run-cloud-build.cloud.goog
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/*"
        backend:
          service:
            name: reactjs-service
            port:
              number: 3000
      - pathType: ImplementationSpecific
        path: "/api/*"
        backend:
          service:
            name: nodejs-service
            port:
              number: 4000
  tls:
    - hosts:
      - frontend.endpoints.mern-cloud-run-cloud-build.cloud.goog
      # secretName: mern-certificate-staging-tls
      secretName: mern-certificate-production-tls